include:
  - project: 'orderlynetwork/orderly-devops/orderly-common/common-ci'
    ref: main
    file: '/common-orderly-network-dev-v2.yaml'
  - project: 'orderlynetwork/orderly-devops/orderly-common/common-ci'
    ref: main
    file: '/common-orderly-network-qa-evm.yaml'

variables:
  SERVICE_NAME: dmm
  IMAGE_NAME: dmm

deploy_dev_v2:
  stage: deploy
  image:
    name: asia-northeast1-docker.pkg.dev/woo-orderly/orderly-devops/curl
    entrypoint: [""]
  script:
    - echo "Trigger dev v2 helm deploying ... "
    - curl -X POST --fail -F token=${DEPLOY_DMM_PRJ_TOKEN} -F "ref=aliyun-dev" -F "variables[SERVICE_NAME]=${SERVICE_NAME}" -F "variables[TAG]=${CI_COMMIT_TAG}" https://gitlab.com/api/v4/projects/${DEPLOY_DMM_PRJ_ID}/trigger/pipeline
  when: manual
  only:
    - tags
  tags:
    - dev
    - build

deploy_qa_evm:
  stage: deploy
  image:
    name: asia-northeast1-docker.pkg.dev/woo-orderly/orderly-devops/curl
    entrypoint: [""]
  script:
    - echo "Trigger qa-evm helm deploying ... "
    - curl -X POST --fail -F token=${DEPLOY_DMM_PRJ_TOKEN} -F "ref=aliyun-qa" -F "variables[SERVICE_NAME]=${SERVICE_NAME}" -F "variables[TAG]=${CI_COMMIT_TAG}" https://gitlab.com/api/v4/projects/${DEPLOY_DMM_PRJ_ID}/trigger/pipeline
  when: manual
  only:
    - tags
  tags:
    - dev
    - build


stages:
  - check_tag
  - build_docker
  - tg_bot
  - deploy
  - update_sdk_version

tg_bot:
  stage: tg_bot
  image:
    name: asia-northeast1-docker.pkg.dev/woo-orderly/orderly-devops/gcloud
    entrypoint: [""]
  script:
    - echo ${CI_COMMIT_TAG}
    - echo ${IMAGE_NAME}
    - TAG_EXISTS=$(gcloud container images list-tags asia-northeast1-docker.pkg.dev/woo-orderly/orderly-network/${IMAGE_NAME} --filter="tags=${CI_COMMIT_TAG}" --format="value(tags)")
    - echo ${TAG_EXISTS}
    - |
      if [ "${TAG_EXISTS}" ]; then
        echo "done, send tg bot message"
        curl -X POST "https://api.telegram.org/bot8337546037:AAGnHx9w_qVdiiqwYYQF7OQFcGkbd8-rDOs/sendMessage" -d "chat_id=-1002252117640&text=${IMAGE_NAME} tag: ${CI_COMMIT_TAG} done"
      fi
  only:
    - tags
  tags:
    - dev
    - build

# Update dependencies job triggered by SDK project
update_sdk_version:
  stage: update_sdk_version
  image:
    name: asia-northeast1-docker.pkg.dev/woo-orderly/orderly-devops/node:20 
  script:
    - |
      npm install -g pnpm@9
      pnpm install --frozen-lockfile
      pnpm release
  rules:
    - if: '$PACKAGE_VERSION && $TRIGGER_BRANCH'
      when: always
  tags:
    - dev
    - build